"""add user watchlist

Revision ID: 939040ff6a73
Revises: 97916a7d3180
Create Date: 2026-09-29 01:49:46.689566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '939040ff6a73'
down_revision: Union[str, Sequence[str], None] = '97916a7d3180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlistitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', name='uq_watchlist_user_symbol')
    )
    op.create_index(op.f('ix_watchlistitem_symbol'), 'watchlistitem', ['symbol'], unique=False)
    op.create_index(op.f('ix_watchlistitem_user_id'), 'watchlistitem', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlistitem_user_id'), table_name='watchlistitem')
    op.drop_index(op.f('ix_watchlistitem_symbol'), table_name='watchlistitem')
    op.drop_table('watchlistitem')
    # ### end Alembic commands ###
